In [ ]:
import numpy as np

def create_population(pop_size, n, m):
    population = []
    for _ in range(pop_size):
        individual = np.random.randint(2, size=(n, m))
        population.append(individual)
    return population


In [ ]:
def fitness(individual):
    # Exemple de fonction de fitness : somme des valeurs dans la matrice
    return np.sum(individual)


In [ ]:
def select_parents(population, num_parents):
    parents = []
    for _ in range(num_parents):
        # Sélection aléatoire d'individus
        selected = np.random.choice(len(population))
        parents.append(population[selected])
    return parents

def crossover(parents, offspring_size):
    offspring = []
    for _ in range(offspring_size):
        # Sélection aléatoire de deux parents
        parent1_idx, parent2_idx = np.random.choice(len(parents), size=2, replace=False)
        parent1 = parents[parent1_idx]
        parent2 = parents[parent2_idx]
        # Point de croisement
        crossover_point = np.random.randint(1, len(parent1))
        # Création de l'enfant
        child = np.vstack((parent1[:crossover_point], parent2[crossover_point:]))
        offspring.append(child)
    return offspring

def mutate(offspring, mutation_rate):
    for i in range(len(offspring)):
        if np.random.random() < mutation_rate:
            # Mutation aléatoire
            mutation_point = np.random.randint(0, len(offspring[i]))
            offspring[i][mutation_point] = 1 - offspring[i][mutation_point]
    return offspring


In [ ]:
def genetic_algorithm(pop_size, n, m, num_generations, num_parents, mutation_rate):
    population = create_population(pop_size, n, m)
    for generation in range(num_generations):
        # Calcul de la fitness pour chaque individu
        fitness_values = [fitness(individual) for individual in population]
        
        # Sélection des meilleurs parents
        parents = select_parents(population, num_parents)
        
        # Croisement
        offspring = crossover(parents, pop_size - num_parents)
        
        # Mutation
        offspring = mutate(offspring, mutation_rate)
        
        # Remplacement de la population par les enfants
        population = parents + offspring
        
        # Affichage de la meilleure fitness dans cette génération
        print("Génération {}: Meilleure fitness = {}".format(generation+1, max(fitness_values)))

    # Retourne la meilleure solution trouvée
    return population[np.argmax(fitness_values)]

# Exemple d'utilisation
best_solution = genetic_algorithm(pop_size=100, n=5, m=10, num_generations=20, num_parents=20, mutation_rate=0.1)
print("Meilleure solution trouvée :")
print(best_solution)


In [1]:
import numpy as np

# Définition de l'ensemble de base
base_set = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])

def create_population(pop_size, n, m):
    population = []
    for _ in range(pop_size):
        individual = np.random.randint(2, size=(n, m))
        population.append(individual)
    return population

def fitness(partition):
    # Exemple de fonction de fitness : maximiser la similarité intra-groupe et minimiser la similarité inter-groupe
    
    # Calcul des sommes pour chaque groupe
    group_sums = np.sum(partition * base_set[:, :, np.newaxis], axis=1)
    
    
    # Plus la similarité intra-groupe est grande et la similarité inter-groupe est petite, meilleure est la partition
    return intra_group_similarity - inter_group_similarity

def select_parents(population, num_parents):
    # Sélection des parents basée sur la fitness
    fitness_values = [fitness(individual) for individual in population]
    selected_parents_indices = np.argsort(fitness_values)[-num_parents:]
    return [population[i] for i in selected_parents_indices]

def crossover(parents, offspring_size):
    offspring = []
    for _ in range(offspring_size):
        parent1_idx, parent2_idx = np.random.choice(len(parents), size=2, replace=False)
        parent1 = parents[parent1_idx]
        parent2 = parents[parent2_idx]
        crossover_point = np.random.randint(1, len(parent1))
        child = np.vstack((parent1[:crossover_point], parent2[crossover_point:]))
        offspring.append(child)
    return offspring

def mutate(offspring, mutation_rate):
    for i in range(len(offspring)):
        if np.random.random() < mutation_rate:
            mutation_point = np.random.randint(0, len(offspring[i]))
            offspring[i][mutation_point] = 1 - offspring[i][mutation_point]
    return offspring

def genetic_algorithm(pop_size, n, m, num_generations, num_parents, mutation_rate):
    population = create_population(pop_size, n, m)
    for generation in range(num_generations):
        fitness_values = [fitness(individual) for individual in population]
        parents = select_parents(population, num_parents)
        offspring = crossover(parents, pop_size - num_parents)
        offspring = mutate(offspring, mutation_rate)
        population = parents + offspring
        print("Génération {}: Meilleure fitness = {}".format(generation+1, max(fitness_values)))
    return population[np.argmax(fitness_values)]

best_partition = genetic_algorithm(pop_size=100, n=4, m=4, num_generations=20, num_parents=20, mutation_rate=0.1)
print("Meilleure partition trouvée :")
print(best_partition)


Génération 1: Meilleure fitness = -8908
Génération 2: Meilleure fitness = -2988
Génération 3: Meilleure fitness = -508
Génération 4: Meilleure fitness = -508
Génération 5: Meilleure fitness = 0
Génération 6: Meilleure fitness = 0
Génération 7: Meilleure fitness = 0
Génération 8: Meilleure fitness = 0
Génération 9: Meilleure fitness = 0
Génération 10: Meilleure fitness = 0
Génération 11: Meilleure fitness = 0
Génération 12: Meilleure fitness = 0
Génération 13: Meilleure fitness = 0
Génération 14: Meilleure fitness = 0
Génération 15: Meilleure fitness = 0
Génération 16: Meilleure fitness = 0
Génération 17: Meilleure fitness = 0
Génération 18: Meilleure fitness = 0
Génération 19: Meilleure fitness = 0
Génération 20: Meilleure fitness = 0
Meilleure partition trouvée :
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [38]:
import numpy as np

# Définition du nombre de caractéristiques par candidat
num_features = 10



def fitness(partition):
   

def select_parents(population, num_parents):
    # Sélection des parents basée sur la fitness
    fitness_values = [fitness(individual) for individual in population]
    selected_parents_indices = np.argsort(fitness_values)[-num_parents:]
    return [population[i] for i in selected_parents_indices]

def crossover(parents, offspring_size):
    offspring = []
    for _ in range(offspring_size):
        parent1_idx, parent2_idx = np.random.choice(len(parents), size=2, replace=False)
        parent1 = parents[parent1_idx]
        parent2 = parents[parent2_idx]
        crossover_point = np.random.randint(1, len(parent1))
        child = np.vstack((parent1[:crossover_point], parent2[crossover_point:]))
        offspring.append(child)
    return offspring

def mutate(offspring, mutation_rate):
    for i in range(len(offspring)):
        if np.random.random() < mutation_rate:
            mutation_point = np.random.randint(0, len(offspring[i]))
            offspring[i][mutation_point] = 1 - offspring[i][mutation_point]
    return offspring

def genetic_algorithm(pop_size, n, m, num_generations, num_parents, mutation_rate):
    population = create_population(pop_size, n, m)
    for generation in range(num_generations):
        fitness_values = [fitness(individual) for individual in population]
        parents = select_parents(population, num_parents)
        offspring = crossover(parents, pop_size - num_parents)
        offspring = mutate(offspring, mutation_rate)
        population = parents + offspring
        print("Génération {}: Meilleure fitness = {}".format(generation+1, max(fitness_values)))
    return population[np.argmax(fitness_values)]

# Générer les candidats
candidates = generate_candidates(num_candidates=50, num_features=num_features)


# Exécution de l'algorithme génétique
best_partition = genetic_algorithm(pop_size=100, n=4, m=4, num_generations=20, num_parents=20, mutation_rate=0.1)
print("Meilleure partition trouvée :")
print(best_partition)


Génération 1: Meilleure fitness = -14296
Génération 2: Meilleure fitness = -3416
Génération 3: Meilleure fitness = -2752
Génération 4: Meilleure fitness = -508
Génération 5: Meilleure fitness = -508
Génération 6: Meilleure fitness = -508
Génération 7: Meilleure fitness = -508
Génération 8: Meilleure fitness = -508
Génération 9: Meilleure fitness = -508
Génération 10: Meilleure fitness = -508
Génération 11: Meilleure fitness = -508
Génération 12: Meilleure fitness = -508
Génération 13: Meilleure fitness = -508
Génération 14: Meilleure fitness = -508
Génération 15: Meilleure fitness = -508
Génération 16: Meilleure fitness = -508
Génération 17: Meilleure fitness = -508
Génération 18: Meilleure fitness = -508
Génération 19: Meilleure fitness = -508
Génération 20: Meilleure fitness = -508
Meilleure partition trouvée :
[[0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


autre

In [24]:
test =[[1, 0.12, 1.00, 0.90],
[2, 0.97, 0.00, 0.30],
[3, 0.00, 0.64, 0.98],
[4, 1.00, 0.45, 1.00],
[5, 0.35, 0.07, 0.93],
[6, 0.59, 0.84, 0.00]]
test

[[1, 0.12, 1.0, 0.9],
 [2, 0.97, 0.0, 0.3],
 [3, 0.0, 0.64, 0.98],
 [4, 1.0, 0.45, 1.0],
 [5, 0.35, 0.07, 0.93],
 [6, 0.59, 0.84, 0.0]]

In [17]:
TM = np.mean(test,axis = 0)
TM = TM[1:]

array([0.505, 0.5  , 0.685])

In [46]:
g1 =[1,2,3]
g2 = [4,5,6]
res = []

for t in test:
    if t[0] in g1:
        res.append(t)

res

x1b = np.mean(res,axis = 0)[1:]
res = []
for t in test:
    if t[0] in g2:
        res.append(t)

x2b = np.mean(res,axis = 0)[1:]
x2b

D1=(x1b - TM[1:])**2
D2=(x2b - TM[1:])**2

In [47]:
sum(D1+D2)

0.047966666666666664